#! /usr/bin/env bash
#~/20cvpr/myenv/bin/python3 sub.pyz ~/Documents/test_data/video.MP4 ~/Documents/test_data/questions.txt
. ~/20cvpr/myenv/bin/activate
python3 sub/__main__.py ~/Documents/test_data/video.MP4 ~/Documents/test_data/questions.txt
